smash> submitted by Eran
smash> smash> smash> smash> [1] ./printSignals.exe &
[2] sleep 200&
[3] sleep 300&
smash> signal number 9 was sent to pid 2
smash> smash> [1] ./printSignals.exe &
[3] sleep 300&
[4] sleep 400&
smash> smash> smash> smash> smash> smash> signal number 9 was sent to pid 3
smash> signal number 5 was sent to pid 4
smash> received signal number: 5
smash> [1] ./printSignals.exe &
[3] sleep 300&
[4] sleep 500&
smash> smash: sending SIGKILL signal to 3 jobs:
4: ./printSignals.exe &
5: sleep 300&
6: sleep 500&
